apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend-service
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
             name: frontend
             port:
               number: 80
