version: '3'
services:
  eureka:
    image: 'eureka-service:latest'
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    ports:
      - '8761:8761'
  zuul:
    image: 'zuul-server:latest'
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    ports:
      - '8081:8081'
  product:
    image: 'product-service:latest'
    ports:
      - '8090:8090'