version: "3"
services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/certs/cert.pem:/etc/nginx/conf.d/cert.pem
      - ./nginx/certs/key.pem:/etc/nginx/conf.d/key.pem
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "443:443"
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./conf/mysql/:/docker-entrypoint-initdb.d/
    expose:
      - "3306"
    ports:
      - 3306:3306
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --innodb_use_native_aio=0,
        --max_connections=50,
      ]
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:4.3.0.Final
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    expose:
      - "8082"
    ports:
      - 8082:8082
      - 9990:9990
    command: ["-b=0.0.0.0 -Djboss.http.port=8082"]
    depends_on:
      - mysql
  eureka:
    image: "eureka-service:latest"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    ports:
      - "8761:8761"
  zuul:
    image: "zuul-server:latest"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    ports:
      - "8081:8081"
  product:
    image: "product-service:latest"
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom
    ports:
      - "8090:8090"

volumes:
  mysql_data:
    driver: local
