version: "3"
services:
  eureka:
    image: "poc-eureka-server:latest"
    environment:
      - "SPRING_EUREKA=http://eureka:8761/eureka"
    ports:
      - "8761:8761"
  gateway:
    image: "poc-gateway:latest"
    environment:
      - "JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
      - "SPRING_PROFILES_ACTIVE=default,classical"
      - "SPRING_EUREKA=http://eureka:8761/eureka"
    ports:
      - "8050:8050"
  user:
    image: "poc-user-service:latest"
    environment:
      - "JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
      - "SPRING_PROFILES_ACTIVE=default,classical"
      - "SPRING_EUREKA=http://eureka:8761/eureka"
    ports:
      - "8100:8100"
  contactus:
    image: "poc-contact-us-service:latest"
    environment:
      - "JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
      - "SPRING_PROFILES_ACTIVE=default,classical"
      - "SPRING_EUREKA=http://eureka:8761/eureka"
    ports:
      - "8200:8200"
  reactive:
    image: "poc-reactive-web-producer:latest"
    environment:
      - "JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
      - "SPRING_PROFILES_ACTIVE=default,classical"
      - "SPRING_EUREKA=http://eureka:8761/eureka"
    ports:
      - "8300:8300"
  websocket:
    image: "poc-websocket-service:latest"
    environment:
      - "JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
      - "SPRING_PROFILES_ACTIVE=default,classical"
      - "SPRING_EUREKA=http://eureka:8761/eureka"
    ports:
      - "8400:8400"
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mariadb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8888:8080
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.4.7
    volumes:
      - mariadb_data:/var/lib/mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

volumes:
  mariadb_data:
    driver: local
