version: "3.7"

x-common-variables: &common-variables
  eureka.client.serviceUrl.defaultZone: http://eureka:8080/eureka
  eureka.instance.non-secure-port: 8080

services:
  eureka:
    image: "dhananjay12/demo-eureka-server:latest"
    environment:
      <<: *common-variables
    ports:
      - "8761:8080"
  gateway:
    image: "dhananjay12/demo-gateway:latest"
    environment:
      <<: *common-variables
    ports:
      - "8080:8080"
  service-one:
    image: "dhananjay12/demo-service-one:latest"
    environment:
      <<: *common-variables
    ports:
      - "8100:8080"
  service-two:
    image: "dhananjay12/demo-service-two:latest"
    environment:
      <<: *common-variables
    ports:
      - "8200:8080"
  reactive-service:
    image: "dhananjay12/demo-reactive-service:latest"
    environment:
      <<: *common-variables
    ports:
      - "8300:8080"
#  websocket-service:
#    image: "dhananjay12/demo-websocket-service:latest"
#    environment:
#      <<: *common-variables
#    ports:
#      - "8400:8080"
