zuul:
  routes:
    token:
      path: /token/**
      url: http://localhost:8082/auth/realms/master/protocol/openid-connect/token
    product-service:
      path: /product-service/**
      service-id: product-service
      

security:
  oauth2:
    client:
      # From OIDC app
      clientId: frontend
      clientSecret: eb5dccec-dd28-4223-babd-69298cd0ad11
      # From Authorization Server's metadata
      accessTokenUri: http://localhost:8082/auth/realms/master/protocol/openid-connect/token
      userAuthorizationUri: http://localhost:8082/auth/realms/master/protocol/openid-connect/auth
      clientAuthenticationScheme: form
    resource:
       # from your Auth Server's metadata, check .well-known/openid-configuration
      userInfoUri: http://localhost:8082/auth/realms/master/protocol/openid-connect/userinfo
      preferTokenInfo: false         
      jwt: 
        key-value: 
           -----BEGIN PUBLIC KEY-----
           MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjxSGEYYJOfetVYRapUvPCZrXaYo6UdreGjpr6Rd3+I7NJC+AMBxtOHEkcT09l0lCeY/ScvY1oNlg7djl4MaLOZ7tjTajQnoe7j/1i0ap2LhH1Hiyi+BXx6vw6LKuWdKYuaNptwcGw7D0ptaBH3RbrQ7scckPKxImDVKdZB6Siz0BMigPtVFWkwem5Dz6yjRTpKBzvNGirVcGqYmgXNBF+qoOj02bNAsO8KiPREKK6UfK3+q5ITGzy7GGDJ5yTa1dgLYXMwK43cMdAodGWMdd6q1Ky5TRBfFwdigrpMWC+wkcuBEctAfmIhOpbp1qoFH1A4dbXeF5qwtUTt/67xHYDQIDAQAB
           -----END PUBLIC KEY-----