management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  main:
    banner-mode: off
  application:
    name: service-two
  cloud:
    bootstrap:
      enabled: true
    kubernetes:
      enabled: false
      reload:
        enabled: false
  zipkin:
    enabled: false