management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    kubernetes:
      enabled: false
      reload:
        enabled: false