# Log all requests at the Metadata level.
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # - level: Metadata
  - level: RequestResponse
    verbs: ["get","watch","describe"]
    resources:
      - group: ""
        resources: ["endpoints", "services"]
    namespaces: ["test"]