eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${SPRING_EUREKA:http://localhost:8761/eureka/}

spring:
  cloud:
    kubernetes:
      enabled: false
      reload:
        enabled: false