app:
  security:
    exclude-url:
    jwt:
      public-key: ${security.oauth2.resource.jwt.key-value}
      client-id: frontend
   
      
security:
  oauth2:
    resource:            
      jwt: 
        key-value: 
           -----BEGIN PUBLIC KEY-----
           MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl8LHiG25MXzZY1zWc6TvKmRu0/7dyMql2PtPKxEHoLxVs4p2O78Gk3s8UUsJtBP+/C9BX3QdKuID0bs79XAc+csVm31aruu26bT80SY6pB7ysvu3YBN1NSvfhEOAA1g6eHIGolKQrZiszmlkZF4t2RxlIVHu6BgZIH1GKyhyvPjS/8meBpfpuhW40Zv9MdChw7hO9bzhhZYFA3sef57668os3yCLIM0+C7VUimMzczlVIb9TZ0zJRcintblkyM+P1L8/ifEEXkfC3PqGQnJYHiShkNaZBgsG1Geb4RJLcerADG2zS8Ih4lxn47Ei/RzTTwimH2d+BDsg6tgiBs/LNQIDAQAB
           -----END PUBLIC KEY-----