security:
  basic:
    enabled: true

management:
  security:
    enabled: true

app:
  security:
    jwt:
      authority:
        key: groups

eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA:http://localhost:8761/eureka}
