
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: service-one
  cloud:
    bootstrap:
      enabled: true
    kubernetes:
      enabled: false
      reload:
        enabled: false
  zipkin:
    enabled: false