management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

spring:
  main:
    banner-mode: off
  application:
    name: reactive-service
  cloud:
    kubernetes:
      enabled: false
      config:
        enable-api: false
        enableApi: false
        enabled: false
      reload:
        enabled: false
  zipkin:
    enabled: false