version: "3.7"

x-common-variables: &common-variables
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8080/eureka
  EUREKA_INSTANCE_NONSECUREPORT: 8080
  SPRING_ZIPKIN_ENABLED: 'true'
  SPRING_ZIPKIN_BASEURL: 'http://zipkin:9411'
  SPRING_SLEUTH_SAMPLER_PROBABILITY: 1

services:
  eureka:
    image: "dhananjay12/demo-eureka-server:latest"
    environment:
      <<: *common-variables
    ports:
      - "8761:8080"
#  frontend:
#    image: "dhananjay12/demo-frontend:latest"
#    volumes:
#      - ./config/frontend/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "80:80"
  gateway:
    image: "dhananjay12/demo-gateway:webclient1"
    environment:
      <<: *common-variables
      spring.application.json: "{\n\"spring\":{\n\"cloud\":{\n\"gateway\":{\n\"default-filters\":[\n\"ExternalService\"\n]\n}\n}\n}\n}"
      app.external.service.url: http://service-one:8080/hello
      #spring.cloud.kubernetes.enabled: "false"
      #spring.cloud.kubernetes.leader.auto-startup: "false"
      #spring.cloud.kubernetes.leader.enabled: "false"
      #spring.cloud.kubernetes.secrets.enabled: "false"
      #spring.cloud.kubernetes.discovery.enabled: "false"
      #spring.cloud.kubernetes.config.enabled: "false"
      #spring.cloud.kubernetes.config.enable-api: "false"
      #spring.cloud.bootstrap.enabled: "false"
      #spring.sleuth.reactor.instrumentation-type: DECORATE_QUEUES
    ports:
      - "8080:8080"
  service-one:
    image: "dhananjay12/demo-service-one:2.7.7"
    environment:
      <<: *common-variables
    ports:
      - "8100:8080"
  service-two:
    image: "dhananjay12/demo-service-two:2.7.7"
    environment:
      <<: *common-variables
    ports:
      - "8200:8080"
  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
